# Generated by Django 2.2.10 on 2020-03-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial_admin_index"),
    ]

    operations = []
