# Generated by Django 3.2.12 on 2022-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamodel", "0014_alter_notificatie_forwarded_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificatieresponse",
            name="attempt",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Indicates to which delivery attempt this response belongs.",
                verbose_name="attempt",
            ),
        ),
    ]
