# Generated by Django 4.2.15 on 2025-01-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0016_alter_abonnement_callback_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filter",
            unique_together={("filter_group", "key")},
        ),
    ]
