# Generated by Django 3.2.13 on 2022-06-27 14:46

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Notificatie = apps.get_model("datamodel", "Notificatie")
    for row in Notificatie.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0016_notificatie_uuid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
