# Generated by Django 4.2.17 on 2025-02-11 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0017_alter_filter_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="auth",
            field=models.CharField(
                help_text='Content of the Authorization header when sending notifications to the "Callback URL", for example: Bearer a4daa31...',
                max_length=1000,
                verbose_name="Authorisation header",
            ),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="callback_url",
            field=models.URLField(
                help_text="The URL to which notifications should be sent. This URL should point to an API that is suitable to receive notifications.",
                verbose_name="Callback URL",
            ),
        ),
        migrations.AlterField(
            model_name="kanaal",
            name="documentatie_link",
            field=models.URLField(
                blank=True,
                help_text="URL to documentation.",
                verbose_name="Documentation link",
            ),
        ),
        migrations.AlterField(
            model_name="kanaal",
            name="filters",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="List of possible filter attributes for a KANAAL. These filter attributes can be used when creating an ABONNEMENT",
                size=None,
                verbose_name="filters",
            ),
        ),
        migrations.AlterField(
            model_name="kanaal",
            name="naam",
            field=models.CharField(
                help_text='Name of the KANAAL (also called "Exchange") that represents the source.',
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
