# Generated by Django 5.2.7 on 2025-11-21 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0018_abonnement_english_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='send_cloudevents',
            field=models.BooleanField(default=False, help_text='Whether to send notifications as cloudevents to the subscribed callback (default: `false`).', verbose_name='Send cloudevents'),
        ),
        migrations.CreateModel(
            name='CloudEvent',
            fields=[
                ('int_id', models.BigAutoField(help_text='internal id', primary_key=True, serialize=False, verbose_name='ID')),
                ('id', models.CharField(help_text='event id', max_length=255, verbose_name='id')),
                ('source', models.CharField(help_text='event source', max_length=255, verbose_name='source')),
                ('specversion', models.CharField(help_text='cloudevent spec version used by the event', max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\d+)\\.(\\d+)')], verbose_name='specversion')),
                ('type', models.CharField(help_text='event type on which can be subscribed. Example: nl.overheid.zaken.zaak.created', max_length=255, verbose_name='type')),
                ('datacontenttype', models.CharField(blank=True, help_text='content type of the (optional) cloudevent data. Example: application/json', max_length=255, verbose_name='data content type')),
                ('dataschema', models.CharField(blank=True, help_text='A schema that the data must follow', max_length=255, verbose_name='dataschema')),
                ('subject', models.CharField(blank=True, help_text='the events subject. Example: an uuid of a zaak', max_length=255, verbose_name='subject')),
                ('time', models.DateTimeField(blank=True, help_text='the timestamp of when the event happened', null=True, verbose_name='time')),
                ('data', models.TextField(blank=True, help_text='extra data using the format defined in datacontentype', null=True, verbose_name='data')),
            ],
            options={
                'unique_together': {('id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CloudEventFilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_substring', models.CharField(help_text='a substring of an event type that the subscription will watch for', max_length=255, verbose_name='type substring')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudevent_filtergroups', to='datamodel.abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='CloudEventResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1, help_text='Indicates to which delivery attempt this response belongs.', verbose_name='attempt')),
                ('exception', models.CharField(blank=True, max_length=1000)),
                ('response_status', models.IntegerField(null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.abonnement')),
                ('cloudevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.cloudevent')),
            ],
        ),
    ]
