# Generated by Django 5.2.8 on 2025-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0019_abonnement_send_cloudevents_cloudevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='auth_client_id',
            field=models.CharField(blank=True, help_text='**EXPERIMENTEEL** The client ID used to construct the JSON Web Token', max_length=255, verbose_name='Client Id'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('no_auth', 'No authorization'), ('api_key', 'API key'), ('zgw', 'ZGW client_id + secret'), ('oauth2_client_credentials', 'OAuth2 client credentials flow')], default='api_key', help_text='**EXPERIMENTEEL** Required fields per auth type: * `api_key`: `auth`, * `zgw`: `client_id`, `secret`, * `oauth2_client_credentials`: `client_id`, `secret`, `oauth2_token_url`', max_length=30, verbose_name='authorization type'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='oauth2_scope',
            field=models.CharField(blank=True, help_text='**EXPERIMENTEEL** Optional scope for OAuth2 token requests', max_length=255, verbose_name='OAuth2 Scope'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='oauth2_token_url',
            field=models.URLField(blank=True, help_text='**EXPERIMENTEEL** OAuth2 token endpoint for client credentials flow. ', max_length=1000, verbose_name='OAuth2 Token URL'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='secret',
            field=models.CharField(blank=True, help_text='**EXPERIMENTEEL** OAuth2 client secret, if applicable', max_length=255, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='auth',
            field=models.CharField(blank=True, help_text='Content of the Authorization header when sending notifications to the "Callback URL", for example: Bearer a4daa31...', max_length=1000, verbose_name='Authorisation header'),
        ),
    ]
