# Generated by Django 5.2.7 on 2025-10-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0019_cloudevent_cloudeventfiltergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudEventResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1, help_text='Indicates to which delivery attempt this response belongs.', verbose_name='attempt')),
                ('exception', models.CharField(blank=True, max_length=1000)),
                ('response_status', models.IntegerField(null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.abonnement')),
                ('cloudevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.cloudevent')),
            ],
        ),
    ]
