# Generated by Django 5.2.8 on 2026-01-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0020_abonnement_auth_client_id_abonnement_auth_type_and_more"),
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the client",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="abonnement_service_client",
                to="simple_certmanager.certificate",
            ),
        ),
        migrations.AddField(
            model_name="abonnement",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the server",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="abonnement_service_server",
                to="simple_certmanager.certificate",
            ),
        ),
    ]
