# Generated by Django 5.2.7 on 2025-11-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0020_cloudeventresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='send_cloudevents',
            field=models.BooleanField(default=False, help_text='Whether to send notifications as cloudevents and cloudevents themselves', verbose_name='Send cloudevents'),
        ),
    ]
