# Generated by Django 5.2.8 on 2026-01-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0021_abonnement_client_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudEventFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Sleutel')),
                ('value', models.CharField(max_length=1000, verbose_name='Waarde')),
                ('cloud_event_filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='datamodel.cloudeventfiltergroup')),
            ],
            options={
                'verbose_name': 'filter-onderdeel',
                'verbose_name_plural': 'filter-onderdelen',
                'ordering': ('id',),
                'unique_together': {('cloud_event_filter_group', 'key')},
            },
        ),
    ]
