# Generated by Django 5.2.11 on 2026-03-03 14:22

from django.db import migrations


def merge_auth_client_id_field(apps, schema_editor):
    """
    The `auth_client_id` field was added in version 1.15.0, but there was already an
    existing `client_id` field. This migration fills the value of `client_id` with the
    value of `auth_client_id` (if `client_id` is empty)
    """
    Abonnement = apps.get_model("datamodel", "Abonnement")
    for abonnement in Abonnement.objects.iterator():
        if abonnement.auth_client_id and not abonnement.client_id:
            abonnement.client_id = abonnement.auth_client_id
            abonnement.save(update_fields=["client_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("datamodel", "0022_cloudeventfilter"),
    ]

    operations = [
        migrations.RunPython(merge_auth_client_id_field, migrations.RunPython.noop)
    ]
