# Generated by Django 5.2.8 on 2026-02-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0022_cloudeventfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notification', 'notification'), ('cloudevent', 'cloudevent')], max_length=255, verbose_name='type')),
                ('task_args', models.JSONField(verbose_name='task args')),
                ('execute_at', models.DateTimeField(verbose_name='execute_at')),
                ('attempt', models.PositiveSmallIntegerField(verbose_name='attempt')),
                ('cloudevent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='datamodel.cloudevent')),
                ('notificatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='datamodel.notificatie')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='datamodel.abonnement')),
            ],
        ),
    ]
