# Generated by Django 5.2.11 on 2026-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamodel", "0023_merge_duplicate_client_id_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abonnement",
            name="auth_client_id",
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="The client ID used to construct the JSON Web Token",
                max_length=100,
                verbose_name="Client ID",
            ),
        ),
    ]
