# Generated by Django 5.2.11 on 2026-03-16 14:00

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0024_remove_abonnement_auth_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notification', 'notification'), ('cloudevent', 'cloudevent')], help_text='type of notification', max_length=255, verbose_name='type')),
                ('task_args', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='the contents of the notification', verbose_name='task args')),
                ('execute_after', models.DateTimeField(help_text='the datetime after which the notification should be executed', verbose_name='execute_after')),
                ('attempt', models.PositiveSmallIntegerField(help_text='the amount of attempts that have been made to send the notification', verbose_name='attempt')),
                ('in_progress', models.BooleanField(default=False, help_text='indicates whether the notification is currently in progress', verbose_name='in progress')),
                ('cloudevent', models.ForeignKey(blank=True, help_text='the related cloudevent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='datamodel.cloudevent')),
                ('notificatie', models.ForeignKey(blank=True, help_text='the related notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='datamodel.notificatie')),
                ('subs', models.ManyToManyField(help_text='the subscriptions that should receive the notification', related_name='scheduled_notifications', to='datamodel.abonnement')),
            ],
        ),
    ]
