# Generated by Django 5.2.11 on 2026-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0025_schedulednotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotification',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='in progress'),
        ),
    ]
