# Generated by Django 5.2.17 on 2026-10-09 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0025_schedulednotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='auth',
            field=models.CharField(
                blank=True,
                help_text='Content of the Authorization header when sending notifications to the "Callback URL", for example: Bearer a4daa31...',
                verbose_name='Authorisation header'
            ),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='callback_url',
            field=models.CharField(
                help_text='The URL to which notifications should be sent. This URL should point to an API that is suitable to receive notifications.',
                validators=[django.core.validators.URLValidator()],
                verbose_name='Callback URL'
            ),
        ),
    ]
