# Generated by Django 2.2.20 on 2021-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudEventConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oin",
                    models.CharField(
                        help_text="The OIN that will be used in the source field of the cloudevent.",
                        max_length=20,
                        verbose_name="OIN",
                    ),
                ),
            ],
            options={
                "verbose_name": "CloudEvents configuration",
                "verbose_name_plural": "CloudEvents configurations",
            },
        ),
    ]
