services:
  webhook:
    build: ./webhook
    container_name: webhook_simulator
    ports:
      - "8008:8000"
    restart: unless-stopped
    networks:
      - open-notificaties-dev
    volumes:
      - ./webhook/main.py:/app/main.py

networks:
  open-notificaties-dev:
    name: open-notificaties-dev
