name: generate-postman-collection

on:
  push:
    paths:
      - "src/openapi.yaml"
      - ".github/workflows/generate-postman-collection.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-postman-collection:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-postman-collection.yml@initial-setup
    with:
      schema-path: 'src/openapi.yaml'
