name: lint-oas

on:
  push:
    paths:
      - "src/openapi.yaml"
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-lint-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/lint-oas.yml@v1
    with:
      schema-path: 'src/openapi.yaml'
