name: check-oas

on:
  push:
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v5
    with:
      python-version: '3.11'
      django-settings-module: 'nrc.conf.ci'
      schema-command: bin/generate_schema.sh
