
name: OAS

on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  oas:
    name: Checks
    uses: maykinmedia/open-api-workflows/.github/workflows/oas.yml@v5
    with:
      python-version: '3.12'
      apt-packages: 'libgdal-dev gdal-bin'
      django-settings-module: nrc.conf.ci
      oas-generate-command: ./bin/generate_schema.sh
      schema-path: src/openapi.yaml
      oas-artifact-name: nrc-api-oas
      node-version-file: '.nvmrc'
      spectral-version: '^6.15.0'
      openapi-to-postman-version: '^5.0.0'
      postman-artifact-name: nrc-api-postman-collection
      openapi-generator-version: '^2.20.0'